// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvdzkJenRMc182vn0SZ7HlZsvnmORMIoQ',
    appId: '1:206479033887:android:5f68b050e4faab46ba372a',
    messagingSenderId: '206479033887',
    projectId: 'messages-13187',
    storageBucket: 'messages-13187.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBpOs3rS3krMZ8AujU5Ltr3H2-OicSYEQ',
    appId: '1:206479033887:ios:456e3ff5ae560438ba372a',
    messagingSenderId: '206479033887',
    projectId: 'messages-13187',
    storageBucket: 'messages-13187.firebasestorage.app',
    iosBundleId: 'thrive.messages',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBpOs3rS3krMZ8AujU5Ltr3H2-OicSYEQ',
    appId: '1:206479033887:ios:456e3ff5ae560438ba372a',
    messagingSenderId: '206479033887',
    projectId: 'messages-13187',
    storageBucket: 'messages-13187.firebasestorage.app',
    iosBundleId: 'thrive.messages',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAga_CNCjGDrVdUhytVrZS7bYZcTa_Z4YQ',
    appId: '1:206479033887:web:231e53e1e7088727ba372a',
    messagingSenderId: '206479033887',
    projectId: 'messages-13187',
    authDomain: 'messages-13187.firebaseapp.com',
    storageBucket: 'messages-13187.firebasestorage.app',
    measurementId: 'G-XG09CDXKR3',
  );
}
